version: "3.8"

services:
  web:
    build: ./
    image: searchimages
    container_name: searchimages
    command: sh -c "python3 manage.py makemigrations; python3 manage.py migrate; python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db

  histogram:
    build:
      context: ./histogram
    container_name: histogram
    ports:
    - 8080:8080
    depends_on:
      - db
    command: java -Djava.security.egd=file:/dev/./urandom -jar /histogram/target/histogram-0.0.1-SNAPSHOT.jar
    volumes:
      - /indexing:/indexing

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=searchimages
      - POSTGRES_PASSWORD=searchimages
      - POSTGRES_DB=searchimages
    ports:
      - 5432:5432

volumes:
  postgres_data:
