version: "3.3"
services:
  web:
    image: "${IMAGE}:searchimages"
    container_name: searchimages
    command: sh -c "python manage.py makemigrations --noinput; python manage.py migrate; python manage.py collectstatic --no-input --clear; gunicorn searchImages.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - static_volume:/static
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - .env

  histogram:
    image: "${IMAGE}:histogram"
    container_name: histogram
    command: java -Djava.security.egd=file:/dev/./urandom -jar /histogram/target/histogram-0.0.1-SNAPSHOT.jar
    restart: always
    expose:
      - 8080

  nginx:
    image: "${IMAGE}:nginx"
    container_name: nginx
    restart: always
    volumes:
      - static_volume:/static
      - media_volume:/usr/src/app/mediafiles
      - /certs:/etc/nginx/certs
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    env_file:
      - .env
    depends_on:
      - web
      - histogram

volumes:
  static_volume:
  media_volume: