version: "3.8"

services:
  web:
    build: ./
    image: &web web
    container_name: web
    command: sh -c "python manage.py makemigrations; python manage.py migrate; python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=searchImages
      - POSTGRES_PASSWORD=searchImages
      - POSTGRES_DB=searchImages

  minio:
    image: minio/minio:RELEASE.2020-12-16T05-05-17Z
    container_name: minio
    volumes:
    - data:/data
    ports:
      - 9000:9000
    env_file:
      - .env.dev
    command: server /data/minio
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
#  rabbit:
#    image: library/rabbitmq:3.8-management
#    container_name: rabbit
#    hostname: dimatroickij
#    env_file:
#      - .env.dev
#    ports:
#      - 15672:15672
#      - 5672:5672
#
#  celery:
#    #build: ./smarthome
#    image: *web
#    container_name: celery
#    env_file:
#      - .env.dev
#    command: celery worker -A searchImages
#    volumes:
#      - ./searchImages:/usr/src/app
#    depends_on:
#      - rabbit
#      - db
#    links:
#      - rabbit
#      - db
#
#  celery_beat:
#    image: *web
#    container_name: celery_beat
#    env_file:
#      - .env.dev
#    command: celery -A searchImages beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler --pidfile=/tmp/celeryd.pid
#    volumes:
#      - ./searchImages:/usr/src/app
#    depends_on:
#      - rabbit
#      - db
#    links:
#      - rabbit
#      - db

volumes:
  postgres_data:
  data: