version: "3.3"

services:
  web:
    build:
      context: ./
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    container_name: searchimages
    volumes:
      - static_volume:/static
      - media_volume:/usr/src/app/mediafiles
    expose:
      - 8000
    env_file:
      - .env

  histogram:
    build:
      context: ./histogram
      cache_from:
        - "${HISTOGRAM_IMAGE}"
    image: "${HISTOGRAM_IMAGE}"
    container_name: histogram
    expose:
      - 8080
    command: java -Djava.security.egd=file:/dev/./urandom -jar /histogram/target/histogram-0.0.1-SNAPSHOT.jar

  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    container_name: nginx
    volumes:
      - static_volume:/static
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 80:80
      - 8080:8080
    depends_on:
      - web
      - histogram

volumes:
  static_volume:
  media_volume:

