#!/bin/sh

echo DEBUG=$DEBUG >> .env
echo DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS >> .env
echo SECRET_KEY=$SECRET_KEY >> .env
echo SQL_DATABASE=$SQL_DATABASE >> .env
echo SQL_ENGINE=$SQL_ENGINE >> .env
echo SQL_HOST=$SQL_HOST >> .env
echo SQL_PASSWORD=$SQL_PASSWORD >> .env
echo SQL_PORT=$SQL_PORT >> .env
echo SQL_USER=$SQL_USER >> .env
echo CI_REGISTRY_USER=$CI_REGISTRY_USER   >> .env
echo CI_JOB_TOKEN=$CI_JOB_TOKEN  >> .env
echo CI_REGISTRY=$CI_REGISTRY  >> .env
echo IMAGE=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME >> .env

