# Generated by Django 3.1.5 on 2021-01-05 12:03

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='src',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to=''),
        ),
    ]
