# Generated by Django 3.1.5 on 2021-01-05 20:45

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210105_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, unique=True, upload_to='dev/img', verbose_name='Изображение'),
        ),
    ]
