# Generated by Django 3.1.5 on 2021-01-05 21:09

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_remove_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='media', verbose_name='Изображение'),
        ),
    ]
