# Generated by Django 3.1.5 on 2021-01-05 21:16

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20210105_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
