# Generated by Django 3.1.5 on 2021-01-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20210124_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='histogram',
            field=models.JSONField(verbose_name='Гистограмма в JSON формате'),
        ),
    ]
