# Generated by Django 3.1.7 on 2021-02-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_auto_20210124_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='details',
            field=models.JSONField(null=True, verbose_name='Данные о сегментации изображения'),
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
    ]
